// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }




// import "./globals.css";
// import Header from "@/components/Header";
// import { Roboto } from "next/font/google"; // font
// import { Red_Hat_Text } from "next/font/google"; // font

// const roboto = Roboto({ subsets: ["latin"] }); // font
// // const rht = Red_Hat_Text({ subsets: ["latin"] }); // font

// export const metadata = {
//   title: "My Portfolio",
//   description: "A Next.js portfolio with lazy load and animations",
// };

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//       <body className={`${roboto.className} bg-white text-gray-900`}>
//         <Header />
//         <main>{children}</main>
//       </body>
//     </html>
//   );
// }


// import "./globals.css";
// import Header from "@/components/Header";
// import { Roboto } from "next/font/google";
// import ClientWrapper from "@/components/ClientWrapper";

// const roboto = Roboto({ subsets: ["latin"], weight: ["300", "400", "500", "700"] });

// export const metadata = {
//   title: "My Portfolio",
//   description: "A Next.js portfolio with lazy load and animations",
// };

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//       <body className={`${roboto.className} bg-white text-gray-900`}>
//         <Header />
//         <ClientWrapper>{children}</ClientWrapper>
//       </body>
//     </html>
//   );
// }

import "./globals.css";
import Header from "@/components/Header";
import { Roboto } from "next/font/google";
import ClientWrapper from "@/components/ClientWrapper";
import { Suspense } from "react";
import { Analytics } from "@vercel/analytics/next" // Vercel Analytics

const roboto = Roboto({ subsets: ["latin"], weight: ["300", "400", "500", "700"] });

export const metadata = {
  title: "Jeremy Chen",
  description: "A Next.js portfolio with lazy load and animations",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} bg-white text-gray-900`}>
        {/* 🔻 這一整塊是 CSR + useSearchParams 的世界 */}
        <Suspense fallback={null}>
          <Header />
          <ClientWrapper>{children}</ClientWrapper>
          <Analytics /> {/* Vercel Analytics */}
        </Suspense>
      </body>
    </html>
  );
}





